### ISSUE TITLE
Simplified module/package structure

### ISSUE THREAD

**Issue by bplommer** [trace4cats/trace4cats#701]
When trialling t4c at $work I've had a lot of complaints about the number of different packages and modules that are needed for the core functionality. Here are a few tentative suggestions for reducing barriers to adoption:

### modules
- combine `model` into `kernel`
- combine  `exporter-common`, `base` and `inject` into `core`

### packages
- move contents of `model` and `inject` packages into either the base package or `trace` and `span` packages
- move contents of `kernel` package into either the base package or a `span` package
- consider changing the base package from `io.janstenpickle.trace4cats` to just `trace4cats`

Any thoughts on this?

**Comment by catostrophe** [comment]
@bplommer I'm definitely for this simplification.

We're about to cut a new release soon. Actually I should have done it last week, but still have one PR open. It would be nice to include this change into the new 0.13.0 release.

The only thing that bothers me is how to make the upgrade smooth for the end users. Are you experienced with scalafix so that we could include a fix that can be applied by Scala Steward automagically?

**Comment by janstenpickle** [comment]
I like the proposal too, with hindsight I went a bit far with the modularisation 😅.

I would like to get thoughts on combining `inject` and `core` though. When I first created this project I wanted a separation between the internals (span, completers and exporters) and means of injection. This was so that it could be used with Natchez without having to bring in our `inject` code and so that the standalone components (agent and collector) would not need to import the `inject` code either. What is everyone's thoughts here? Maybe keeping `inject` a separate module, but still making the proposed package changes?

> The only thing that bothers me is how to make the upgrade smooth for the end users. Are you experienced with scalafix so that we could include a fix that can be applied by Scala Steward automagically?

I agree with @catostrophe here, I think we'd need to ship some scalafix to apply the package changes, but I don't have any experience using it.

Maybe we should split this into two issues: Module consildation and package naming.

**Comment by bplommer** [comment]
> I would like to get thoughts on combining `inject` and `core` though. When I first created this project I wanted a separation between the internals (span, completers and exporters) and means of injection. This was so that it could be used with Natchez without having to bring in our `inject` code and so that the standalone components (agent and collector) would not need to import the `inject` code either. What is everyone's thoughts here? Maybe keeping `inject` a separate module, but still making the proposed package changes?

How about chopping up the modules differently - moving the current `core` into `kernel` and changing `inject` to `core` – that would fit with the pattern of (for example) cats-effect, where `kernel` has the components typically needed by downstream libraries and `core` has the components needed for building an app.

Re Natchez - are we talking about incorporating components that use t4c into an app that uses Natchez for end-to-end tracing? Do you have an example of how that works? (I see the `trace4cats-natchez` module does have a dependency on `inject`, which I guess is for the more common reverse scenario.)

> I agree with @catostrophe here, I think we'd need to ship some scalafix to apply the package changes, but I don't have any experience using it.

I could definitely do that for the packages, though I may not have time for a couple of weeks. It should be possible to do something hacky for the modules, but I’m not sure scala steward can apply scalafixes to build files.

> Maybe we should split this into two issues: Module consolidation and package naming.

Sounds good. I made a start with module consolidation (it required creating a new tests module to allow the tests to depend on the test kit) so I’ll open a PR today.

**Comment by janstenpickle** [comment]
> How about chopping up the modules differently - moving the current core into kernel and changing inject to core – that would fit with the pattern of (for example) cats-effect, where kernel has the components typically needed by downstream libraries and core has the components needed for building an app.

This sounds good, I like it! Depending on how we move things around there may also be scope for `std` library, similar to cats-effect, but happy to stick with `kernel` and `core` to start with.

> Re Natchez - are we talking about incorporating components that use t4c into an app that uses Natchez for end-to-end tracing? Do you have an example of how that works? (I see the trace4cats-natchez module does have a dependency on inject, which I guess is for the more common reverse scenario.)

The `trace4cats-natchez` library has a couple of concerns: firstly providing interop between Natchez `Trace` and t4c `Trace`, and secondly (to enable this) providing a Natchez `Trace` implementation using the code in `core` and `kernel`, which is just like any of the existing Natchez integrations with Java tracing libraries. This means you could use Natchez in your codebase end-to-end without using t4c`inject`. [Here](https://github.com/trace4cats/trace4cats-natchez/blob/master/modules/natchez/src/main/scala/io/janstenpickle/trace4cats/natchez/Trace4CatsTracer.scala) is the integration code for a Natchez `Entrypoint` that allows users to work with t4c without using the `inject` code directly.

The reason `inject` exists is because it better exposes some of the features in t4c such as lazily evaluated labels, which stops labels from being computed if the span is dropped. When using Natchez they become eagerly evaluated.

> but I’m not sure scala steward can apply scalafixes to build files

Ah yes, this could be a problem! Maybe we could still publish certain artifacts with the legacy name where they have been rolled into a library that is below them in the tree and is commonly used by end users (this may just apply to `inject)

> I made a start with module consolidation (it required creating a new tests module to allow the tests to depend on the test kit) so I’ll open a PR today.

Amazing, thank you!

**Comment by bplommer** [comment]
> Maybe we could still publish certain artifacts with the legacy name where they have been rolled into a library that is below them in the tree and is commonly used by end users (this may just apply to `inject)

That sounds good. We can also leave a trail of deprecated aliases behind.

**Comment by bplommer** [comment]
Hi, sorry for the silence on this - realistically I'm unlikely to move further on this in the next month or two, so you may wish to go ahead with the next release.

**Comment by janstenpickle** [comment]
No worries @bplommer, we'll proceed with the release as is and target these changes for the next one

**Comment by janstenpickle** [comment]
@bplommer I'm happy to do some more on this if I get some time in the next few weeks. From what we discussed, I think this was the plan WRT modules:

`model`, `core` -> `kernel`
`base`, `inject`, `exporter-common` ->  (new) `core`

Let's tackle the package names in a different PR

**Comment by catostrophe** [comment]
I think `base` shouldn't be merged. It's universal and may be used without t4c

**Comment by janstenpickle** [comment]
Yes, good point. I'll edit the plan above.

**Comment by bplommer** [comment]
> I think `base` shouldn't be merged. It's universal and may be used without t4c

It's basically an optics library and an mtl library tailored for t4c, right? It seems like it should either be split out int general-purpose optics and mtl libraries, or kept as a kind of internal detail of t4c.

**Comment by catostrophe** [comment]
It contains only basic lenses needed for t4c. As for mtl part - keeping it as a separate module will prevent us from randomly spoiling it with model leaks.
I don't mind if we move it to a separate lib though.

**Comment by janstenpickle** [comment]
Maybe now would be a good time to revisit the decision not to include a dependency on `tofu-kernel` and `tofu-optics`? We orginially didn't do this because we didn't need all of the functionality from Tofu, but if we're considering a more general purpose repo split out from this one then it's probably worth considering.

**Comment by catostrophe** [comment]
Oh, unfortunately, tofu is not ready for Scala 3.

**Comment by janstenpickle** [comment]
Ahh ok, I missed that. I wonder if we should migrate to Tofu once it is compiling against Scala 3? If we decide to do that, it probably means that we should leave `base` alone.

**Comment by bplommer** [comment]
> Ahh ok, I missed that. I wonder if we should migrate to Tofu once it is compiling against Scala 3? If we decide to do that, it probably means that we should leave `base` alone.

Maybe the name could be more descriptive though - `fp-helpers` or something? The current name sounds like it's a foundational part of t4c itself.

**Comment by janstenpickle** [comment]
Yep, that's a good name. I'd put money on no one depending on it directly at the moment, so safe to rename.

**Comment by catostrophe** [comment]
I think we shouldn't wait for it. I don't know when this happens.

**Comment by catostrophe** [comment]
> consider changing the base package from io.janstenpickle.trace4cats to just trace4cats
I support this. Maybe we should also consider changing maven org?

**Comment by janstenpickle** [comment]
Just to be clear, the package renaming should probably happen in a separate PR

**Comment by janstenpickle** [comment]
@bplommer @catostrophe any thoughts about moving some modules that are currently separate repos back into this one? I thought `trace4cats-natchez` and `trace4cats-http4s` might be good candidates. Natchez so that we can maintain compatbility as a first-class consideration and Http4s as it's the most commonly used integration. `trace4cats-exporter-http` could be a useful one too...

**Comment by bplommer** [comment]
My concern about moving t4c-http4s back in would be supporting different versions. 1.0 won't be out for quite some time but the milestones are beginning to diverge from 0.23 to a degree that people might want to start using it in production soon. How would support for that work in a monorepo?

I think t4c-natchez is a good candidate though.

**Comment by bplommer** [comment]
Could t4c-docs be moved back in?

**Comment by janstenpickle** [comment]
> My concern about moving t4c-http4s back in would be supporting different versions. 1.0 won't be out for quite some time but the milestones are beginning to diverge from 0.23 to a degree that people might want to start using it in production soon. How would support for that work in a monorepo?

Yep good point, it's the same reason we broke out sttp/tapir, let's leave all the http4s bits out

> Could t4c-docs be moved back in?

Yep, I think that's a good candidate too

**Comment by janstenpickle** [comment]
Tracking comment for repo consolidation candidates

`trace4cats-natchez`
`trace4cats-docs`

**Comment by janstenpickle** [comment]
RE some of the module removals, it turns out we can deal with that (to some extent) with ScalaSteward: https://github.com/scala-steward-org/scala-steward/blob/main/docs/artifact-migrations.md. It may result in people ending up with the same artifact imported twice, but I think that's probably OK.

**Comment by catostrophe** [comment]
> https://github.com/scala-steward-org/scala-steward/blob/main/docs/artifact-migrations.md

Yes, this is a known feature. I would suggest it anyway :)

**Comment by catostrophe** [comment]
> Tracking comment for repo consolidation candidates:
> 
> `trace4cats-natchez` `trace4cats-docs`

We have split repos in order to be able to release `t4c-natchez` when a new version of `natchez` is out. Back then we though the core repo would be stable and have less releases than integrations.

**Comment by catostrophe** [comment]
> Could t4c-docs be moved back in?

I don't think so. It has the whole ecosystem as deps.

**Comment by catostrophe** [comment]
First of all, which problems are we going to solve by re-assembling repos into one?

**Comment by janstenpickle** [comment]
The question is, did we go too far separating everything out? If the answer is "no" then I'm happy to leave everything where it is.

I still think Natchez (just to core library) might be a good candidate, just so we can maintain compatability with it. My recent change to `Trace` would have broken this if I hadn't thought about it ahead of time.

**Comment by catostrophe** [comment]
> The question is, did we go too far separating everything out? If the answer is "no" then I'm happy to leave everything where it is.
> 
> I still think Natchez (just its core library) might be a good candidate, just so we can maintain compatability with it. My recent change to `Trace` would have broken this if I hadn't thought about it ahead of time.

Any changes in the core may break anything in other repos.

Maybe we should make a pipeline that builds other repos against changes in the core repo?

**Comment by janstenpickle** [comment]
That's fair. There's two reasons we break out repos that I can think of: 1) we think we may have to support multiple versions of the same dependency. 2) long running integration tests slow down the build/test of this repo. 

I'm not sure Natchez fits in either of these reasons, but there is a third softer reason - it's an integration and not an integral part of t4c. If we think that's a good enough reason for keeping it separate then I'm happy to leave it where it is.

>Maybe we should make a pipeline that builds other repos against changes in the core repo?

I think that might be good, just as long as it doesn't block the main build as 2) will become a problem again.

**Comment by janstenpickle** [comment]
This is now released!
